//#include "C:/Users/larsmark/Documents/openSRI/sri_v1_2/SRI_v1/include/commands.h"
//#include "C:/Users/micke/Documents/openSRI/sri_v1_2/SRI_v1/include/setting_structs.h"
//#include "C:/Users/radio/Documents/openSRI-v1.2/sri_v1_2/SRI_v1/include/commands.h"
//#include "C:/Users/radio/Documents/openSRI-v1.2/sri_v1_2/SRI_v1/include/setting_structs.h"
#include "C:/Users/larsmark/Documents/openSRI-v1.2/sri_v1_2/SRI_v1/include/commands.h"
#include "C:/Users/larsmark/Documents/openSRI-v1.2/sri_v1_2/SRI_v1/include/setting_structs.h"
